language: cpp

compiler:
  - gcc

before_script:
  # create a build folder for the out-of-source build
  - mkdir build_tests_coverage
  # switch to build directory
  - cd build_tests_coverage
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..' Coverage is on by default.
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCLONE_ROMI_LIB_REPOS=ON ..

script:
  # once CMake has done its job we just build using make as usual
  - make
  # if the project uses ctest we can run the tests like this
  - ctest -V

after_success:
  - make rcom_unit_tests_coverage
  - bash <(curl -s https://codecov.io/bash)
