name: CI

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'     
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install websocket-client
          
      - name: Install dependencies
        run: |
          sudo apt install libfluidsynth-dev
          # Only needed when gpsd is added to the build.
          # sudo apt-get install libgps-dev
          
      - name: Install test dependencies
        run: |
          sudo apt install socat

      - name: Create Build Environment & configure CMake
        working-directory: ${{runner.workspace}}/romi-rover-build-and-test
        run: |
          mkdir build_tests
          cd build_tests
          cmake ..
          
      - name: Build
        working-directory: ${{runner.workspace}}/romi-rover-build-and-test
        run: |
          cd build_tests
          make -j4
          
      - name: Test
        working-directory: ${{runner.workspace}}/romi-rover-build-and-test
        run: |
          cd build_tests
          ctest -V
      
      - name: Upload coverage to Codecov
        working-directory: ${{runner.workspace}}/romi-rover-build-and-test
        run: bash <(curl -s https://codecov.io/bash)
      
